spring:
  application:
    name: springboot-demo
  devtools:
    restart:
      enabled: false

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.26.13.116:1111/eureka/
